services:
  redis:
    image: redis:8.10-alpine
    container_name: kener-redis
    restart: unless-stopped
    networks:
      - kener
    volumes:
      - ./redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  kener:
    image: rajnandan1/kener:4.1.2-alpine
    container_name: kener
    restart: unless-stopped
    env_file:
      - ./secrets/kener.env
    environment:
      ORIGIN: https://status.chrs.ro
      REDIS_URL: redis://redis:6379
    networks:
      - kener
      - reverse-proxy
    volumes:
      - ./database:/app/database
    depends_on:
      redis:
        condition: service_healthy

networks:
  kener:
  reverse-proxy:
    external: true
