services:
  haproxy:
    image: haproxytech/haproxy-alpine:3.4.3
    container_name: haproxy
    restart: unless-stopped
    networks:
      - reverse-proxy
      - cloudflare-tunnel
      - monitoring
    volumes:
      - ./config:/usr/local/etc/haproxy:ro
    ports:
      - 127.0.0.1:8404:8404
      - 127.0.0.1:8405:8405

networks:
  reverse-proxy:
    external: true
  cloudflare-tunnel:
    external: true
  monitoring:
    external: true
