services:
  chrs.ro:
    image: ghcr.io/hyssedev/chrs:latest
    container_name: "chrs.ro"
    networks:
      - reverse-proxy
    restart: unless-stopped

networks:
  reverse-proxy:
    external: true