services:
  grafana:
    image: grafana/grafana:13.1.4
    container_name: grafana
    restart: unless-stopped
    networks:
      - reverse-proxy
      - monitoring
    environment:
      GF_SERVER_DOMAIN: grafana.chrs.ro
      GF_SERVER_ROOT_URL: https://grafana.chrs.ro
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_AUTO_ASSIGN_ORG: "true"
      GF_USERS_AUTO_ASSIGN_ORG_ROLE: Admin
      GF_AUTH_PROXY_ENABLED: "true"
      GF_AUTH_PROXY_HEADER_NAME: Remote-User
      GF_AUTH_PROXY_HEADER_PROPERTY: username
      GF_AUTH_PROXY_AUTO_SIGN_UP: "true"
      GF_AUTH_PROXY_HEADERS: Name:Remote-Name Email:Remote-Email
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_BASIC_ENABLED: "false"
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_ANALYTICS_CHECK_FOR_UPDATES: "false"
    volumes:
      - ./data:/var/lib/grafana
      - ./provisioning/datasources/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml:ro
      - ./provisioning/dashboards/default.yml:/etc/grafana/provisioning/dashboards/default.yml:ro
      - ./dashboards:/var/lib/grafana-dashboards:ro

networks:
  reverse-proxy:
    external: true
  monitoring:
    external: true
