services:
  tinyauth:
    image: ghcr.io/tinyauthapp/tinyauth:v5.1.3
    container_name: tinyauth
    restart: unless-stopped
    networks:
      - reverse-proxy
    environment:
      TINYAUTH_APPURL: https://auth.chrs.ro
      TINYAUTH_AUTH_USERSFILE: /run/secrets/users
      TINYAUTH_AUTH_SECURECOOKIE: "true"
      TINYAUTH_AUTH_SESSIONEXPIRY: "86400"
      TINYAUTH_AUTH_SESSIONMAXLIFETIME: "604800"
      TINYAUTH_ANALYTICS_ENABLED: "false"
      TINYAUTH_LABELPROVIDER: none
    secrets:
      - users
    volumes:
      - ./data:/data

secrets:
  users:
    file: ./secrets/users

networks:
  reverse-proxy:
    external: true
