services:
  dynacat:
    container_name: dynacat
    image: panonim/dynacat
    restart: unless-stopped
    networks:
      - reverse-proxy
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
    env_file: .env

networks:
  reverse-proxy:
    external: true