services:
  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.internal.chrs.ro/
      - GF_PLUGINS_PREINSTALL=yesoreyeram-infinity-datasource
    ports:
      - 127.0.0.1:3001:3000
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboard:/etc/grafana/provisioning/dashboards
      - ./provisioning/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.147.0
    container_name: victoriametrics
    restart: always
    ports:
      - 127.0.0.1:8428:8428
      - 127.0.0.1:8089:8089
      - 127.0.0.1:8089:8089/udp
      - 127.0.0.1:2003:2003
      - 127.0.0.1:2003:2003/udp
      - 127.0.0.1:4242:4242
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--influxListenAddr=:8089"
    volumes:
      - vmdata:/storage
    networks:
      - monitoring

  vmagent:
    image: victoriametrics/vmagent:v1.147.0
    depends_on:
      - "victoriametrics"
      - "nodeexporter"
    ports:
      - 127.0.0.1:8429:8429
    volumes:
      - vmagentdata:/vmagentdata
      - ./scrape-config.yml:/etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    networks:
      - monitoring
    restart: always

  nodeexporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: nodeexporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring

volumes:
  grafana_storage: {}
  vmdata: {}
  vmagentdata: {}

networks:
  monitoring: