services:
  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.internal.chrs.ro/
      - GF_PLUGINS_PREINSTALL=yesoreyeram-infinity-datasource,victoriametrics-logs-datasource
    ports:
      - 127.0.0.1:3001:3000
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboard:/etc/grafana/provisioning/dashboards
      - ./provisioning/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.147.0
    container_name: victoriametrics
    restart: always
    ports:
      - 127.0.0.1:8428:8428
      - 127.0.0.1:4242:4242
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
    volumes:
      - vmdata:/storage
      - ./scrape-config.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring

  vmalert:
    image: victoriametrics/vmalert:v1.147.0
    container_name: vmalert
    restart: always
    depends_on:
      - victoriametrics
      - alertmanager
    ports:
      - 127.0.0.1:8880:8880
    command:
      - "--datasource.url=http://victoriametrics:8428"
      - "--remoteWrite.url=http://victoriametrics:8428"
      - "--remoteRead.url=http://victoriametrics:8428"
      - "--rule=/etc/alerts/*.yml"
      - "--notifier.url=http://alertmanager:9093"
      - "--external.url=https://grafana.internal.chrs.ro"
    volumes:
      - ./alerts.yml:/etc/alerts/alerts.yml:ro
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:v0.28.1
    container_name: alertmanager
    restart: always
    ports:
      - 127.0.0.1:9093:9093
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./secrets/discord_webhook:/run/secrets/discord_webhook:ro
      - amdata:/alertmanager
    networks:
      - monitoring

  victorialogs:
    image: victoriametrics/victoria-logs:v1.51.0
    container_name: victorialogs
    restart: always
    ports:
      - 127.0.0.1:9428:9428
    command:
      - "--storageDataPath=/vlogs"
    volumes:
      - vldata:/vlogs
    networks:
      - monitoring

  vector:
    image: timberio/vector:0.57.0-alpine
    container_name: vector
    restart: unless-stopped
    depends_on:
      - victorialogs
    ports:
      - "127.0.0.1:5140:5140/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      - vector_data:/var/lib/vector
    networks:
      - monitoring

  nodeexporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: nodeexporter
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring

volumes:
  grafana_storage: {}
  vmdata: {}
  vldata: {}
  vector_data: {}
  amdata: {}

networks:
  monitoring: